### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by yaoguaijiao** [imn5100/spring-boot-websocket-demo#1]
When I started your project, the project prompted me a compile-time exception，This is a screenshot of my error report
![微信图片_20210106143406](https://user-images.githubusercontent.com/48637361/103737248-c80cd780-502c-11eb-8b86-3dd7592563ef.png)

**Comment by yaoguaijiao** [comment]
详细查看了您的信息后，我发现我们都来自同一个国家，你好大哥，能帮我瞅一眼这个bug吗

**Comment by imn5100** [comment]
已解决
